insert into BAND values ('Led Zeppelin')
insert into BAND values ('U2')
insert into BAND values ('The Gaslight Anthem')
insert into BAND values ('Pink Floyd')
insert into BAND values ('Queen')
insert into BAND values ('Modest Mouse')
insert into BAND values ('Anti-Flag')
insert into BAND values ('Ramones')
insert into BAND values ('The Casualties')
insert into BAND values ('The Clash')
insert into BAND values ('Subhumans')
insert into BAND values ('The Adicts')

insert into ARTIST values ('Bruce', 'Springsteen')
insert into ARTIST values ('Elvis', 'Presley')
insert into ARTIST values ('Johnny', 'Cash')
insert into ARTIST values ('Joe', 'Ramone')
insert into ARTIST values ('John', 'Mellencamp')
insert into ARTIST values ('David', 'Bowie')
insert into ARTIST values ('Billy', 'Idol')
insert into ARTIST values ('Paul', 'McCartney')
insert into ARTIST values ('Willie', 'Nelson')
insert into ARTIST values ('Pat', 'Benatar')
insert into ARTIST values ('Jerry-Lee', 'Lewis')
insert into ARTIST values ('Ray', 'Charles')

insert into GENRE values ('JAZZ')
insert into GENRE values ('ROCK')
insert into GENRE values ('FOLK')
insert into GENRE values ('HIP HOP')
insert into GENRE values ('BLUES')
insert into GENRE values ('POP')
insert into GENRE values ('COUNTRY')
insert into GENRE values ('EDM')
insert into GENRE values ('REGGAE')
insert into GENRE values ('CLASSICAL')
insert into GENRE values ('PUNK')
insert into GENRE values ('FUNK')
insert into GENRE values ('SINGING')
insert into GENRE values ('RHYTHM')
insert into GENRE values ('RAP')
insert into GENRE values ('DISCO')
insert into GENRE values ('TECHNO')
insert into GENRE values ('INSTRUMENTAL')
insert into GENRE values ('INDEOENDENT')
insert into GENRE values ('HOUSE')
insert into GENRE values ('DUBSTEP')
insert into GENRE values ('ALTERNATIVE')
insert into GENRE values ('SOUL')
insert into GENRE values ('METAL')
insert into GENRE values ('AMBIENT')
insert into GENRE values ('OPERA')
insert into GENRE values ('ELECTRO')
insert into GENRE values ('TRANCE')
insert into GENRE values ('NEW WAVE')
insert into GENRE values ('BASS')
insert into GENRE values ('ORCHESTRA')
insert into GENRE values ('GOSPEL')
insert into GENRE values ('GRUNGE')
insert into GENRE values ('SKA')
insert into GENRE values ('HARDCORE')
insert into GENRE values ('ELECTRONICA')
insert into GENRE values ('CHANT')
insert into GENRE values ('EXPERIMENTAL')
insert into GENRE values ('BREAKBEAT')
insert into GENRE values ('BIG BAND')
insert into GENRE values ('NOISE')
insert into GENRE values ('DEATH METAL')
insert into GENRE values ('BLACK METAL')


insert into song values ('Black Dog', '00:04:56', null, 1, 2)
insert into song values ('One', '00:04:36', null, 2, 2)
insert into song values ('American Slang', '00:03:41', null, 3, 22)
insert into song values ('Time', '00:06:54', null, 4, 2)
insert into song values ('Bohemian Rhapsody', '00:05:54', null, 5, 2)
insert into song values ('All Night Diner', '00:04:44', null, 6, 22)
insert into song values ('The Press Corpse', '00:03:20', null, 7, 11)
insert into song values ('Were A Happy Family', '00:02:39', null, 8, 11)
insert into song values ('Made In NYC', '00:02:26', null, 9, 11)
insert into song values ('Londons Burning', '00:02:11', null, 10, 11)
insert into song values ('Mickey Mouse Is Dead', '00:02:44', null, 11, 11)
insert into song values ('Viva La Revolution', '00:03:49', null, 12, 11)
insert into song values ('Dancing In The Dark', '00:04:01', 1, null, 2)
insert into song values ('Jailhouse Rock', '00:02:26', 2, null, 2)
insert into song values ('I Walk The Line', '00:02:57', 3, null, 7)
insert into song values ('What A Wonderful World', '00:02:23', 4, null, 2)
insert into song values ('Jack & Diane', '00:04:14', 5, null, 2)
insert into song values ('Under Pressure', '00:04:08', 6, null, 2)
insert into song values ('Live And Let Die', '00:03:15', 8, null, 2)
insert into song values ('One The Road Again', '00:02:33', 9, null, 7)
insert into song values ('Love Is A Battlefield', '00:04:10', 10, null, 2)
insert into song values ('Great Balls Of Fire', '00:01:51', 11, null, 2)
insert into song values ('Hit The Road Jack', '00:02:00', 12, null, 2)
insert into song values ('White Wedding', '00:04:12', 7, null, 2)

insert into ALBUM values ('Led Zeppelin IV', null, 1)
insert into ALBUM values ('Achtungbaby', null, 2)
insert into ALBUM values ('The Gaslight Anthem', null, 3)
insert into ALBUM values ('Dark Side Of The Moon', null, 4)
insert into ALBUM values ('A Night A The Opera', null, 5)
insert into ALBUM values ('Interstate 8', null, 6)
insert into ALBUM values ('For Blood And Empire', null, 7)
insert into ALBUM values ('Rocket To Russia', null, 8)
insert into ALBUM values ('Die Hards', null, 9)
insert into ALBUM values ('The Clash', null, 10)
insert into ALBUM values ('The Day The Country Died', null, 11)
insert into ALBUM values ('Songs Of Praise', null, 12)
insert into ALBUM values ('Pink Cadillac', 1, null)
insert into ALBUM values ('Treat Me Nice', 2, null)
insert into ALBUM values ('Johnny Cash With His Hot And Blue Guitar', 3, null)
insert into ALBUM values ('Dont Worry About Me', 4, null)
insert into ALBUM values ('American Fool', 5, null)
insert into ALBUM values ('Hot Space', 6, null)
insert into ALBUM values ('Honeysuckle Rose', 9, null)
insert into ALBUM values ('Live And Let Die', 8, null)
insert into ALBUM values ('Live From Earth', 10, null)
insert into ALBUM values ('Jerry Lees Greatest', 11, null)
insert into ALBUM values ('Ray Charles Greatest Hits', 12, null)
insert into ALBUM values ('Billy Idol', 7, null)

insert into RECORDCOMPANY values ('Alantic Records', 1, 1)
insert into RECORDCOMPANY values ('Island Records', 2, 2)
insert into RECORDCOMPANY values ('Sideonedummy', 3, 5)
insert into RECORDCOMPANY values ('Harvest Records', 4, 6)
insert into RECORDCOMPANY values ('EMI Elektra', 5, 7)
insert into RECORDCOMPANY values ('Up Records', 6, 8)
insert into RECORDCOMPANY values ('RCA', 7, 9)
insert into RECORDCOMPANY values ('Sire', 8, 10)
insert into RECORDCOMPANY values ('Philips', 8, 10)
insert into RECORDCOMPANY values ('CBS', 10, 12)
insert into RECORDCOMPANY values ('Spiderleg', 11, 13)
insert into RECORDCOMPANY values ('Dwed Wecords', 12, 14)
insert into RECORDCOMPANY values ('Columbia', 13, 15)
insert into RECORDCOMPANY values ('RCA Victor', 14, 16)
insert into RECORDCOMPANY values ('Son', 15, 17)
insert into RECORDCOMPANY values ('Santuary Records', 16, 18)
insert into RECORDCOMPANY values ('Riva', 17, 19)
insert into RECORDCOMPANY values ('Apple', 20, 27)
insert into RECORDCOMPANY values ('Chrysalis', 21, 23)
insert into RECORDCOMPANY values ('ABC-Paramont', 23, 25)

insert into BANDARTIST values (null, 1)
insert into BANDARTIST values (null, 2)
insert into BANDARTIST values (null, 3)
insert into BANDARTIST values (null, 4)
insert into BANDARTIST values (null, 5)
insert into BANDARTIST values (null, 6)
insert into BANDARTIST values (null, 7)
insert into BANDARTIST values (null, 9)
insert into BANDARTIST values (null, 10)
insert into BANDARTIST values (null, 11)
insert into BANDARTIST values (null, 12)
insert into BANDARTIST values (1, null)
insert into BANDARTIST values (2, null)
insert into BANDARTIST values (3, null)
insert into BANDARTIST values (4, 8)
insert into BANDARTIST values (5, null)
insert into BANDARTIST values (6, null)
insert into BANDARTIST values (7, null)
insert into BANDARTIST values (8, null)
insert into BANDARTIST values (9, null)
insert into BANDARTIST values (10, null)
insert into BANDARTIST values (11, null)
insert into BANDARTIST values (12, null)

insert into ALBUMSONG values (1, 1)
insert into ALBUMSONG values (2, 2)
insert into ALBUMSONG values (3, 5)
insert into ALBUMSONG values (4, 6)
insert into ALBUMSONG values (5, 7)
insert into ALBUMSONG values (6, 8)
insert into ALBUMSONG values (7, 9)
insert into ALBUMSONG values (8, 10)
insert into ALBUMSONG values (9, 11)
insert into ALBUMSONG values (10, 12)
insert into ALBUMSONG values (11, 13)
insert into ALBUMSONG values (12, 14)
insert into ALBUMSONG values (13, 15)
insert into ALBUMSONG values (14, 16)
insert into ALBUMSONG values (15, 17)
insert into ALBUMSONG values (16, 18)
insert into ALBUMSONG values (17, 19)
insert into ALBUMSONG values (18, 20)
insert into ALBUMSONG values (19, 22)
insert into ALBUMSONG values (20, 27)
insert into ALBUMSONG values (21, 23)
insert into ALBUMSONG values (22, 24)
insert into ALBUMSONG values (23, 25)
insert into ALBUMSONG values (24, 26)

insert into ALBUMRECORD values (1, 1)
insert into ALBUMRECORD values (2, 2)
insert into ALBUMRECORD values (3, 3)
insert into ALBUMRECORD values (4, 4)
insert into ALBUMRECORD values (5, 5)
insert into ALBUMRECORD values (6, 6)
insert into ALBUMRECORD values (8, 8)
insert into ALBUMRECORD values (8, 9)
insert into ALBUMRECORD values (9, 3)
insert into ALBUMRECORD values (10, 10)
insert into ALBUMRECORD values (11, 11)
insert into ALBUMRECORD values (12, 12)
insert into ALBUMRECORD values (13, 13)
insert into ALBUMRECORD values (14, 14)
insert into ALBUMRECORD values (15, 15)
insert into ALBUMRECORD values (16, 16)
insert into ALBUMRECORD values (17, 17)
insert into ALBUMRECORD values (18, 5)
insert into ALBUMRECORD values (19, 16)
insert into ALBUMRECORD values (20, 27)
insert into ALBUMRECORD values (21, 19)
insert into ALBUMRECORD values (22, 15)
insert into ALBUMRECORD values (23, 20)
insert into ALBUMRECORD values (24, 19)